spring:
  application:
    name: kenect-labs-contacts-api

kenect:
  contacts-api:
    url: https://candidate-challenge-api-489237493095.us-central1.run.app/api/v1/contacts
    token: ${CONTACTS_API_TOKEN}