spring:
  cache:
    type: caffeine
  application:
    name: kenect-labs-contacts-api

server:
  port: 8080
  servlet:
    context-path: /kenect-labs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  paths-to-match: /**

kenect:
  async:
    core-pool-size: 50
    max-pool-size: 100
    queue-capacity: 1000
  contacts-api:
    url: https://candidate-challenge-api-489237493095.us-central1.run.app/api/v1/contacts
    token: ${CONTACTS_API_TOKEN}